 orbs:
   node: circleci/node@4.2.1

 version: 2.1
 workflows:
  app-tests:
    jobs:
#        build: 
#      executor:
#       name: node/default
#       tag: '10.4'
       - node/test


# version: 2.1
# orbs:
#   node: circleci/node@4.2.1
# # orbs:
# #   node: circleci/node@1.1
# jobs:
#   build: 
#     executor:
#       name: node/default
#       tag: '10.4'
#     steps:
#       - checkout
#       - run: npm run test
